config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  resources :recipes, only: [:new, :create, :index]
  resources :recipes do
    collection do
      get 'recipe_edit'
      get 'recipe_update'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks
end

app/models/form/recipe_collection.rb
class Form::RecipeCollection < Form::Base
  attr_accessor :recipes, :user_id
  
  #空のインスタンスを作成する
  def initialize(attributes = {})
    super attributes
    self.recipes = 1.times.map { Recipe.new() } unless self.recipes.present?
  end

  def recipes_attributes=(attributes)
    self.recipes = attributes.map { |_, v| Recipe.new(v) }
  end

  def save
    Recipe.transaction do
      self.recipes.map do |recipe|
        recipe["user_id"] = user_id
        recipe.save
      end
    end
      return true
    rescue => e
      return false
  end

  def update
    Recipe.transaction do
      self.recipes.map do |recipe|
        before_recipe = Recipe.find(recipe.id)
        before_recipe.update(title: recipe.title, image: recipe.image)
      end
    end
      return true
    rescue => e
      return false
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  
  def new
    @form = Form::RecipeCollection.new
  end

  def create
    @form = Form::RecipeCollection.new(recipe_collection_params)
    if @form.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def recipe_edit
    @recipes = current_user.recipes
    @form = Form::RecipeCollection.new
  end

  def update
    @form = Form::RecipeCollection.new(recipe_collection_params)
    if @form.update
      redirect_to action: :index
    else
      render :recipe_edit
    end
  end

  private

  def recipe_collection_params
    params.require(:form_recipe_collection)
    .permit(recipes_attributes: [:id, :title, :image]).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AddForm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<%= link_to "新規投稿", new_recipe_path %>
<%= link_to "ログイン", new_user_session_path %>
<%= link_to "新規登録", new_user_registration_path %>
<%= link_to "ログアウト", destroy_user_session_path %>
<%= link_to "投稿編集", recipe_edit_recipes_path %>

<br>
<br>
<% @recipes.each do |recipe| %>
  <%= recipe.title %>
  <%= recipe.image %> <br>
  <% end %>

app/views/recipes/new.html.erb
<%= form_with model: @form, url: recipes_path, method: :post, local: true do |form| %>

<%#以下が増加する中身%>
  <div id="demo-area" class="form-group">
    <div class="unit input-group">
      <%= form.fields_for :recipes, type:"text" do |f| %>
      <%= f.text_field :title, type:"text", placeholder:"タイトル", id:"title_id_0"%>
      <%= f.text_field :image, type:"text", placeholder:"画像", id:"image_id_0" %>
      <% end %>
      <div class="demo-minus input-group-append">
        <span class="btn btn-danger">−</span>
      </div>
    </div>
  </div>
<%#ここまでが増加する中身%>

<div id="demo-plus" class="btn btn-primary">＋</div>

<%= form.submit "投稿する" %>
<% end %>

app/views/recipes/recipe_edit.html.erb
<%= form_with model: @form, url: recipe_update_recipes_path, method: :put, local: true do |form| %>

<%#以下が増加する中身%>
  <div id="demo-area" class="form-group">
    <div class="unit input-group">
      <%= form.fields_for :recipes, type:"text" do |f| %>
      <%= f.collection_select :id, @recipes, :id, :title, include_blank:"レシピタイトルを選択"%>
      <%= f.text_field :title, type:"text", placeholder:"タイトル", id:"title_id_0"%>
      <%= f.text_field :image, type:"text", placeholder:"画像", id:"image_id_0" %>
      <% end %>
      <div class="demo-minus input-group-append">
        <span class="btn btn-danger">−</span>
      </div>
    </div>
  </div>
<%#ここまでが増加する中身%>

<div id="demo-plus" class="btn btn-primary">＋</div>

<%= form.submit "投稿する" %>
<% end %>